apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-dashboard-config
  namespace: k8s-dashboard
data:
  # 开发环境特定配置
  LOG_LEVEL: "debug"
  LOG_FORMAT: "text"

  # 开发环境数据库
  POSTGRES_HOST: "pgsql-postgresql.middle.svc.cluster.local"
  POSTGRES_DB: "k8s_dashboard"

  # 开发环境 VictoriaMetrics
  VICTORIA_METRICS_URL: "http://vmauth-vmks-victoria-metrics-k8s-stack.victoriametrics.svc.cluster.local:8427"
