apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 引用 base
resources:
  - ../../base

# 补丁
patches:
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml

# 环境特定的标签
labels:
  - pairs:
      environment: dev


# 镜像配置
images:
  - name: k8s-dashboard
    newName: zunshen/k8s-dashboard
    newTag: latest

# 副本数
replicas:
  - name: k8s-dashboard
    count: 1
