apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 命名空间
namespace: k8s-dashboard

# 资源文件
resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml

# 通用标签
labels:
  - pairs:
      app.kubernetes.io/name: k8s-dashboard
      app.kubernetes.io/managed-by: kustomize

# 通用注解
commonAnnotations:
  app.kubernetes.io/version: "v1.0.0"

# 镜像
images:
  - name: k8s-dashboard
    newName: k8s-dashboard
    newTag: latest
