apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-dashboard-sqlite
  namespace: k8s-dashboard
  labels:
    app.kubernetes.io/name: k8s-dashboard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
